[build]
  command = "npm ci && npm install --save-optional @rollup/rollup-linux-x64-gnu && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm ci && npm install --save-optional @rollup/rollup-linux-x64-gnu && npm run build"

[context.deploy-preview]
  command = "npm ci && npm install --save-optional @rollup/rollup-linux-x64-gnu && npm run build"

[context.branch-deploy]
  command = "npm ci && npm install --save-optional @rollup/rollup-linux-x64-gnu && npm run build"
